### PR TITLE
Additional percentiles

### PR DESCRIPTION
**Pull request by b20n**
The 90th percentile is, I hope, of obvious utility. I've added the median into the percentiles proplist in order to simplify access patterns for end users.

### CODE REVIEW

**Comment by joewilliams** [comment]
Thanks Ben, there is a missing '{50, 0.0}' though.

**Comment by b20n** [comment]
Eeep, thanks. Fixed.

**Comment by joewilliams** [comment]
Squash this into one commit and i'll merge.

**Comment by b20n** [comment]
Done and done.

**Pull request merged**
