### PR TITLE
negatives, we drop 'em

### PR DESCRIPTION
**Pull request by joewilliams**
Should address https://github.com/boundary/bear/issues/7

### CODE REVIEW

**Comment by joewilliams** [comment]
Not sure this PR is how we want to deal with it but here it is. Perhaps rather doing it at the highest level (scan_values, scan_values2) it should be done in the stats functions that could break with negative values.

**Comment by joewilliams** [comment]
@russelldb thoughts?

**Comment by russelldb** [comment]
Sort of works.If you create an histo and _only_ add negative values you still get an error:

```
** exception error: no function clause matching bear:scan_values([]) (src/bear.erl, line 173)
 in function  bear:get_statistics/1 (src/bear.erl, line 45)
```

**Comment by joewilliams** [comment]
@russelldb this one works, I'm not sure I like the idea of a general purpose stats library that doesn't accept negative values but in bears use case it might make sense. Thoughts?

**Comment by joewilliams** [comment]
Changed my brain, easy fix.

**Pull request merged**
